# Generated by Django 5.2.4 on 2025-07-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='store_close_time',
            field=models.TimeField(blank=True, default='22:00', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='store_open_time',
            field=models.TimeField(blank=True, default='10:00', null=True),
        ),
    ]
