# Generated by Django 5.2.4 on 2025-07-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_store_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
