# Generated by Django 5.2.4 on 2025-07-10 06:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status_orderitem_preferred_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='barcode_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
