# Generated by Django 5.2.4 on 2025-07-16 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_barcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pickup_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_time',
            field=models.CharField(choices=[('12:00', '12:00 PM'), ('12:30', '12:30 PM'), ('13:00', '13:00 PM'), ('18:00', '6:00 PM'), ('18:30', '6:30 PM')], default='12:00', max_length=10),
        ),
    ]
