# Generated by Django 5.2.4 on 2025-08-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission earned from the vendor for this order', max_digits=10),
        ),
    ]
