# Generated by Django 5.2.4 on 2025-08-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission earned from the vendor for this order', max_digits=10),
        ),
    ]
